name: Update Main B
on:
  push:
    branches: [ main-B ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout target repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: hendraempore/test-B
        ref: main-B
        token: ${{ secrets.GH_TOKEN }}
    - name: Merge update
      run: |
        git remote add source ${{ github.event.repository.html_url }}
        git fetch source main-B
        git merge source/main-B
        git push origin main-B
