name: Update Main B
on:
  push:
    branches: [ main-B ]
jobs:
  sync:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        repository: hendraempore/test-A
        ref: main-B

    - name: Set up Git
      run: |
        git config --global user.name 'hendraempore'
        git config --global user.email 'hendra@empore.co.id'

    - name: Remove Extra Headers
      run: git config --unset-all http.https://github.com/.extraheader

    - name: Add Target Repository
      run: git remote add target https://hendraempore:${{ secrets.GH_TOKEN }}@github.com/hendraempore/test-B.git

    

    - name: Push Changes
      run: |
        git push target main-B
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
