name: Update Main B
on:
  push:
    branches: [ main-B ]
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        repository: hendraempore/test-B
        ref: main-B
        token: ${{ secrets.GH_TOKEN }}

    - name: Add Target Repository
      run: git remote add target https://github.com/hendraempore/test-A.git

    - name: Fetch and Merge Changes from Target Repository
      run: |
        git merge target/main-B

    - name: Push Changes
      run: |
        git push origin main-B
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
