name: Update Main A
on:
  push:
    branches: [ main-A ]
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        repository: hendraempore/test-A
        ref: main-A

    - name: Set up Git
      run: |
        git config --global user.name 'hendraempore'
        git config --global user.email 'hendra@empore.co.id'

    - name: Add Target Repository
      run: git remote add target https://github.com/hendraempore/test-B.git

    - name: Push Changes
      run: |
        git push target main-A
      env:
        GH_TOKEN: ${{ secrets.TARGET_REPO_PAT }}
