name: Update Main A
on:
  push:
    branches: [ main-A ]
jobs:
  synchronization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the source repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "hendraempore"
          git config user.email "hendra@empore.co.id"

      - name: Pull latest changes from the source repository
        run: git pull origin main-A

      - name: Push changes to another repository
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git remote add target https://username:${{ secrets.TARGET_REPO_PAT }}@github.com/hendraempore/test-B.git
          git push target main-A
